# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17fc8f530e16c61801be97db33136bd190ba838eac87c87c17c00b89f88d47379b73d688d3c3e681c3d734f29f25fced4659ace13108c864e226acd0d8a8758b

test:
  secret_key_base: af7f34b1a12bfc5e7fa0cae3ae34291dd0287abbce089ec8f84aa6c107014c58e21373a763937057ff25ddd078781fee0fc329065dda299f610cdc4340c6b774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
